import { Courses } from "../types/types";

export const public_api_courses: string =
  "https://64413df4792fe886a8a23776.mockapi.io";

export const public_api_auth_login: string =
  "https://fakestoreapi.com/auth/login";

export const public_api_users: string = "https://fakestoreapi.com/users";

export const listCourse: Courses[] = [
  {
    title: "Modern JavaScript Frontend Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Comprehensive course on modern JavaScript for building responsive web applications.",
    tag: "frontend",
    level: "beginner",
    price: "50.00",
    lessons: 120,
    createBy: "John Doe",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "1",
  },
  {
    title: "Mastering React.js",
    image: "https://loremflickr.com/640/480",
    description:
      "A deep dive into building scalable and efficient applications with React.js.",
    tag: "frontend",
    level: "intermediate",
    price: "80.00",
    lessons: 150,
    createBy: "Jane Smith",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "2",
  },
  {
    title: "Node.js for Backend Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn to build fast, scalable backend services using Node.js and Express.",
    tag: "backend",
    level: "beginner",
    price: "70.00",
    lessons: 110,
    createBy: "Chris Anderson",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "3",
  },
  {
    title: "PHP and Laravel: Backend Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Master PHP and Laravel for modern backend development and RESTful API creation.",
    tag: "backend",
    level: "intermediate",
    price: "60.00",
    lessons: 130,
    createBy: "Sara Collins",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "4",
  },
  {
    title: "Fullstack Web Development with MERN",
    image: "https://loremflickr.com/640/480",
    description:
      "A complete guide to building full-stack applications using MongoDB, Express, React, and Node.js.",
    tag: "fullstack",
    level: "advanced",
    price: "100.00",
    lessons: 180,
    createBy: "Alex Johnson",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "5",
  },
  {
    title: "SQL and Database Management",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn SQL and relational database management using MySQL and PostgreSQL.",
    tag: "database",
    level: "beginner",
    price: "40.00",
    lessons: 90,
    createBy: "Emily Roberts",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "6",
  },
  {
    title: "NoSQL Databases: MongoDB Masterclass",
    image: "https://loremflickr.com/640/480",
    description:
      "Master MongoDB for NoSQL databases and learn how to handle big data efficiently.",
    tag: "database",
    level: "intermediate",
    price: "65.00",
    lessons: 100,
    createBy: "Olivia Blake",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "7",
  },
  {
    title: "Android Development with Kotlin",
    image: "https://loremflickr.com/640/480",
    description:
      "Become proficient in building Android mobile applications using Kotlin.",
    tag: "mobile",
    level: "beginner",
    price: "75.00",
    lessons: 130,
    createBy: "David Clark",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "8",
  },
  {
    title: "iOS App Development with Swift",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn how to create sleek and efficient iOS applications using Swift.",
    tag: "mobile",
    level: "intermediate",
    price: "90.00",
    lessons: 140,
    createBy: "Sophia Martinez",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "9",
  },
  {
    title: "Learn Python Programming",
    image: "https://loremflickr.com/640/480",
    description:
      "A comprehensive guide to Python for all types of applications from web development to data science.",
    tag: "language",
    level: "beginner",
    price: "55.00",
    lessons: 100,
    createBy: "Michael Thompson",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "10",
  },
  {
    title: "Mastering Java Programming",
    image: "https://loremflickr.com/640/480",
    description:
      "Advanced concepts in Java for building enterprise-level applications.",
    tag: "language",
    level: "advanced",
    price: "85.00",
    lessons: 160,
    createBy: "Laura Peterson",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "11",
  },
  {
    title: "Angular: Complete Guide",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn Angular to build modern, scalable, and maintainable web applications.",
    tag: "frontend",
    level: "intermediate",
    price: "85.00",
    lessons: 140,
    createBy: "Daniel Brown",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "12",
  },
  {
    title: "Vue.js: Beginner to Advanced",
    image: "https://loremflickr.com/640/480",
    description:
      "Master Vue.js for creating dynamic and powerful user interfaces.",
    tag: "frontend",
    level: "beginner",
    price: "70.00",
    lessons: 100,
    createBy: "Karen Lee",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "13",
  },
  {
    title: "Django for Web Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn Django, the powerful Python-based web framework for backend development.",
    tag: "backend",
    level: "intermediate",
    price: "75.00",
    lessons: 120,
    createBy: "Tom Nguyen",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "14",
  },
  {
    title: "Ruby on Rails: Web App Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Build fast and scalable web applications using Ruby on Rails.",
    tag: "backend",
    level: "intermediate",
    price: "80.00",
    lessons: 130,
    createBy: "Jessica Turner",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "15",
  },
  {
    title: "Flutter: Mobile App Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Build beautiful, natively compiled mobile applications using Flutter.",
    tag: "mobile",
    level: "beginner",
    price: "65.00",
    lessons: 110,
    createBy: "Ryan Smith",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "16",
  },
  {
    title: "React Native: Cross-Platform Apps",
    image: "https://loremflickr.com/640/480",
    description: "Create cross-platform mobile applications with React Native.",
    tag: "mobile",
    level: "intermediate",
    price: "90.00",
    lessons: 125,
    createBy: "Linda Williams",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "17",
  },
  {
    title: "Go Programming for Backend",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn Go programming language to build robust backend services.",
    tag: "language",
    level: "beginner",
    price: "60.00",
    lessons: 90,
    createBy: "Mark Davis",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "18",
  },
  {
    title: "C# and .NET Core: Web Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Develop modern web applications with C# and the .NET Core framework.",
    tag: "fullstack",
    level: "advanced",
    price: "95.00",
    lessons: 160,
    createBy: "Sam Harris",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "19",
  },
  {
    title: "GraphQL: API Development",
    image: "https://loremflickr.com/640/480",
    description: "Master GraphQL for building efficient and flexible APIs.",
    tag: "backend",
    level: "intermediate",
    price: "80.00",
    lessons: 115,
    createBy: "Monica Gray",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "20",
  },
  {
    title: "Svelte: Fast Frontend Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn Svelte to build high-performance web applications with minimal complexity.",
    tag: "frontend",
    level: "beginner",
    price: "55.00",
    lessons: 90,
    createBy: "Oliver Hughes",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "21",
  },
  {
    title: "Bootstrap 5: Responsive Web Design",
    image: "https://loremflickr.com/640/480",
    description:
      "Master Bootstrap 5 to create responsive, mobile-first websites easily.",
    tag: "frontend",
    level: "beginner",
    price: "40.00",
    lessons: 70,
    createBy: "Maria Garcia",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "22",
  },
  {
    title: "Next.js: Server-Side React",
    image: "https://loremflickr.com/640/480",
    description:
      "Build fast and scalable web applications using Next.js and server-side rendering.",
    tag: "fullstack",
    level: "intermediate",
    price: "75.00",
    lessons: 100,
    createBy: "Lucas Martin",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "23",
  },
  {
    title: "Spring Boot: Java Microservices",
    image: "https://loremflickr.com/640/480",
    description: "Learn Spring Boot for building scalable Java microservices.",
    tag: "backend",
    level: "advanced",
    price: "85.00",
    lessons: 140,
    createBy: "Sophia Lee",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "24",
  },
  {
    title: "Kubernetes: Orchestration for Microservices",
    image: "https://loremflickr.com/640/480",
    description:
      "Master Kubernetes for container orchestration and manage microservices architecture efficiently.",
    tag: "backend",
    level: "advanced",
    price: "95.00",
    lessons: 130,
    createBy: "Ethan Thompson",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "25",
  },
  {
    title: "Docker: Containerization from Scratch",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn Docker to build, ship, and run distributed applications in containers.",
    tag: "backend",
    level: "intermediate",
    price: "65.00",
    lessons: 110,
    createBy: "Hannah Moore",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "26",
  },
  {
    title: "Ionic Framework: Cross-Platform Mobile Apps",
    image: "https://loremflickr.com/640/480",
    description:
      "Develop hybrid mobile applications using the Ionic framework and web technologies.",
    tag: "mobile",
    level: "beginner",
    price: "50.00",
    lessons: 90,
    createBy: "Emma White",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "27",
  },
  {
    title: "Rust Programming: Systems and Web Development",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn Rust programming for building fast and secure systems and web applications.",
    tag: "language",
    level: "intermediate",
    price: "80.00",
    lessons: 120,
    createBy: "Liam Martinez",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "28",
  },
  {
    title: "TypeScript: Supercharge Your JavaScript",
    image: "https://loremflickr.com/640/480",
    description:
      "Master TypeScript to write more robust, type-safe JavaScript applications.",
    tag: "language",
    level: "intermediate",
    price: "55.00",
    lessons: 95,
    createBy: "Jack Wilson",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "29",
  },
  {
    title: "Elixir and Phoenix Framework: Scalable Web Applications",
    image: "https://loremflickr.com/640/480",
    description:
      "Learn Elixir and Phoenix framework for building fault-tolerant and scalable web applications.",
    tag: "backend",
    level: "advanced",
    price: "90.00",
    lessons: 125,
    createBy: "Mia Johnson",
    createAt: "2024-09-11T08:53:47.394Z",
    id: "30",
  },
];
